package com.pwc.newfind.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pwc.newfind.db.entity.FavouriteCompany;
import com.pwc.newfind.db.entity.FavouriteIndustry;
import com.pwc.newfind.db.entity.User;
import com.pwc.newfind.db.entity.FindingTitle;

import com.pwc.newfind.db.FavouriteCompanyDao;
import com.pwc.newfind.db.FavouriteIndustryDao;
import com.pwc.newfind.db.UserDao;
import com.pwc.newfind.db.FindingTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favouriteCompanyDaoConfig;
    private final DaoConfig favouriteIndustryDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig findingTitleDaoConfig;

    private final FavouriteCompanyDao favouriteCompanyDao;
    private final FavouriteIndustryDao favouriteIndustryDao;
    private final UserDao userDao;
    private final FindingTitleDao findingTitleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favouriteCompanyDaoConfig = daoConfigMap.get(FavouriteCompanyDao.class).clone();
        favouriteCompanyDaoConfig.initIdentityScope(type);

        favouriteIndustryDaoConfig = daoConfigMap.get(FavouriteIndustryDao.class).clone();
        favouriteIndustryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        findingTitleDaoConfig = daoConfigMap.get(FindingTitleDao.class).clone();
        findingTitleDaoConfig.initIdentityScope(type);

        favouriteCompanyDao = new FavouriteCompanyDao(favouriteCompanyDaoConfig, this);
        favouriteIndustryDao = new FavouriteIndustryDao(favouriteIndustryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        findingTitleDao = new FindingTitleDao(findingTitleDaoConfig, this);

        registerDao(FavouriteCompany.class, favouriteCompanyDao);
        registerDao(FavouriteIndustry.class, favouriteIndustryDao);
        registerDao(User.class, userDao);
        registerDao(FindingTitle.class, findingTitleDao);
    }
    
    public void clear() {
        favouriteCompanyDaoConfig.clearIdentityScope();
        favouriteIndustryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        findingTitleDaoConfig.clearIdentityScope();
    }

    public FavouriteCompanyDao getFavouriteCompanyDao() {
        return favouriteCompanyDao;
    }

    public FavouriteIndustryDao getFavouriteIndustryDao() {
        return favouriteIndustryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FindingTitleDao getFindingTitleDao() {
        return findingTitleDao;
    }

}
